development:
  adapter: postgresql
  database: hackathononboarder_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: hackathononboarder_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: hackathononboarder_production
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  database: hackathononboarder_staging
  pool: 5
  timeout: 5000
